import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@telegram-apps/telegram-ui/dist/styles.css'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<head>
				<Script
					strategy='beforeInteractive'
					src='https://telegram.org/js/telegram-web-app.js?56'
				/>
			</head>
			<body className={inter.className}>
				<div>{children}</div>
			</body>
		</html>
	)
}
